// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAylx9HHNhFUM4JZjI-84NJ8IuUtJ1C5MA',
    appId: '1:115336743052:web:01d2eec688412fc66093a9',
    messagingSenderId: '115336743052',
    projectId: 'latin-one-4',
    authDomain: 'latin-one-4.firebaseapp.com',
    storageBucket: 'latin-one-4.appspot.com',
    measurementId: 'G-E9BQ7TJ967',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1GNoWLG3t_uqtWO0CO0oc3u6eQRvitBI',
    appId: '1:115336743052:android:c6cbdba4b2b8bce06093a9',
    messagingSenderId: '115336743052',
    projectId: 'latin-one-4',
    storageBucket: 'latin-one-4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCn23NQow1fpYFMv6L51QgqlczoW7nA7Ak',
    appId: '1:115336743052:ios:3e23984ffc1aff8c6093a9',
    messagingSenderId: '115336743052',
    projectId: 'latin-one-4',
    storageBucket: 'latin-one-4.appspot.com',
    iosBundleId: 'com.example.latinOne',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCn23NQow1fpYFMv6L51QgqlczoW7nA7Ak',
    appId: '1:115336743052:ios:3e23984ffc1aff8c6093a9',
    messagingSenderId: '115336743052',
    projectId: 'latin-one-4',
    storageBucket: 'latin-one-4.appspot.com',
    iosBundleId: 'com.example.latinOne',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAylx9HHNhFUM4JZjI-84NJ8IuUtJ1C5MA',
    appId: '1:115336743052:web:5e571ed5836f72be6093a9',
    messagingSenderId: '115336743052',
    projectId: 'latin-one-4',
    authDomain: 'latin-one-4.firebaseapp.com',
    storageBucket: 'latin-one-4.appspot.com',
    measurementId: 'G-5WWC3Q17RP',
  );

}